server {
  listen 4300;
  server_name _;
  location ^~ /modules/todo-list/ {
    rewrite ^/modules/todo-list/(.*)$ /$1 break;
    root /usr/share/nginx/html;
    try_files $uri =404;
  }
  location = /health/ready {
    access_log off;
    return 200 'ready';
    add_header Content-Type text/plain;
  }
}
